name: Deploy
on:
  push:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install step
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build step
        run: npm run build
        env:
          VITE_APP_VERSION: ${{ github.sha }}
          VITE_API_URL: ${{ vars.VITE_API_URL }}

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: 'longthreat-ui'
          entrypoint: 'https://jsr.io/@std/http/1.0.8/file_server.ts'
          root: 'dist'

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
