name: Deploy
on:
  push:
    branches: next
  pull_request:
    branches: next

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "npm install"

      - name: Build step
        run: "npm run build"
        env:
          VITE_API_URL: https://hal3-next.deno.dev        

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "backchat-next-ui"
          entrypoint: "https://deno.land/std@0.217.0/http/file_server.ts"
          root: "dist"
